
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create

# TODO: Lägg till OAuth2 config här (Google/GitHub)
spring.security.oauth2.client.registration.github.client-id=Ov23liScRJLr807O9KCU
spring.security.oauth2.client.registration.github.client-secret=7eee653e920e5a3e58cc04038877839c83aff052